# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publishing

on:
  push:
    branches: [ master ]

jobs:
  frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn install
      working-directory: frontend
    - name: Build
      run: yarn run build
      working-directory: frontend
    - name: Build
      run: yarn run deploy
      working-directory: frontend
